server:
  port: 4300

spring:
  application:
    name: producttrial
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      poolName: HikariPoolZZZ

management:
  endpoints:
    web:
      exposure:
        include: '*'